import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import { createElement as h } from 'react';
import { parseDocumentContent, parseInlineFormatting } from '../../shared/documentFormatting.js';

// No JSX in this file -- client/api/*.js isn't run through Vite/Babel's
// JSX transform (unlike client/src/*.jsx), so plain React.createElement
// calls are used throughout, same as the viability test this was proven
// against before writing the real route.

const styles = StyleSheet.create({
  page: { paddingTop: 50, paddingBottom: 50, paddingHorizontal: 48, fontSize: 11, fontFamily: 'Helvetica', color: '#1a1714' },
  title: { fontSize: 16, marginBottom: 4 },
  meta: { fontSize: 9, color: '#6b6b6b', marginBottom: 20 },
  heading1: { fontSize: 16, marginTop: 4, marginBottom: 10 },
  heading2: { fontSize: 13, marginTop: 14, marginBottom: 8 },
  heading3: { fontSize: 11.5, marginTop: 10, marginBottom: 6 },
  paragraph: { marginBottom: 8, lineHeight: 1.5 },
  listItem: { marginBottom: 4, marginLeft: 14, lineHeight: 1.5 },
  bold: { fontFamily: 'Helvetica-Bold' }
});

const HEADING_STYLES = { 1: styles.heading1, 2: styles.heading2, 3: styles.heading3 };

function renderInline(text, keyPrefix) {
  return parseInlineFormatting(text).map((run, i) =>
    h(Text, { key: `${keyPrefix}-${i}`, style: run.bold ? styles.bold : undefined }, run.text)
  );
}

function formatDate(iso) {
  if (!iso) return '';
  try {
    return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  } catch {
    return '';
  }
}

// Renders a documents-table row to a PDF Buffer. Pagination is automatic
// -- @react-pdf/renderer wraps content across pages on its own, no manual
// page-break logic needed (confirmed with a long multi-paragraph test
// document before this was wired into the real route).
export async function renderDocumentPdf(document) {
  const blocks = parseDocumentContent(document.content);

  const children = blocks.map((block, i) => {
    if (block.type === 'heading') {
      const style = HEADING_STYLES[Math.min(block.level, 3)] || styles.heading3;
      return h(Text, { key: i, style }, renderInline(block.text, `h${i}`));
    }
    if (block.type === 'list') {
      return h(
        View,
        { key: i },
        block.items.map((item, j) => h(Text, { key: j, style: styles.listItem }, '•  ', renderInline(item, `li${i}-${j}`)))
      );
    }
    return h(Text, { key: i, style: styles.paragraph }, renderInline(block.text, `p${i}`));
  });

  const doc = h(
    Document,
    null,
    h(
      Page,
      { size: 'A4', style: styles.page },
      h(Text, { style: styles.title }, document.title || 'Untitled Document'),
      h(Text, { style: styles.meta }, `Generated by LawScribe -- ${formatDate(document.created_at)}`),
      ...children
    )
  );

  return renderToBuffer(doc);
}

// Safe filename derived from the document title -- strips anything that
// isn't alphanumeric/space/hyphen/underscore so it can't break the
// Content-Disposition header or produce a garbled downloaded filename.
export function sanitizeFilename(title) {
  const base = (title || 'document')
    .trim()
    .replace(/[^a-z0-9 _-]/gi, '')
    .replace(/\s+/g, '-');
  return base || 'document';
}
