import Anthropic from '@anthropic-ai/sdk';
import { getSupabaseAdmin, getUserFromToken } from './_lib/supabaseAdmin.js';
import { checkAndIncrementRateLimit, getClientIp } from './_lib/rateLimit.js';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY
});

// Authenticated: identified per-user, generous limit for real iterative
// drafting.
const AUTHENTICATED_RATE_LIMIT = 20;
// Anonymous (the public homepage demo, see DemoGenerator.jsx): per-IP,
// matching client/src/lib/demoRateLimit.js's existing client-side cap
// exactly (3/hour) so the server-side limit reinforces, rather than
// contradicts, what the demo's own UI already promises the visitor.
const ANONYMOUS_RATE_LIMIT = 3;

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    return res.status(500).json({ error: 'Server misconfigured: ANTHROPIC_API_KEY missing' });
  }

  // Now required unconditionally (previously only ANTHROPIC_API_KEY was
  // needed) -- rate limiting below needs Supabase regardless of whether
  // the caller turns out to be authenticated or anonymous.
  const missingVars = ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'].filter((name) => !process.env[name]);
  if (missingVars.length > 0) {
    console.error(`Missing required environment variable(s): ${missingVars.join(', ')}`);
    return res.status(500).json({ error: `Server misconfigured: missing ${missingVars.join(', ')}` });
  }

  const { prompt, documentType } = req.body || {};

  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required.' });
  }

  const supabase = getSupabaseAdmin();

  // Auth is optional here on purpose -- this route serves both the
  // authenticated dashboard generator AND the public, logged-out homepage
  // demo (DemoGenerator.jsx via generateDocument.js). No Authorization
  // header at all is a legitimate anonymous demo request, not an error.
  // A header that IS present but fails to resolve to a real user
  // (expired/invalid token) is different -- that's a signed-in user's
  // session going stale mid-use, not a demo visitor -- so it gets a
  // proper 401 the frontend reacts to the same way as every other
  // authenticated write in this app (see handlePotentialSessionExpiry in
  // AppShell.jsx), rather than silently downgrading them to the
  // anonymous tier's much lower rate limit with no explanation.
  let user = null;
  if (req.headers.authorization) {
    user = await getUserFromToken(supabase, req.headers.authorization);
    if (!user) {
      return res.status(401).json({ error: 'Unauthorized' });
    }
  }

  // Org/plan status is deliberately NOT checked here. Unlike
  // documents.js/clients.js, this route never reads or writes a row that
  // has an org_id/user_id to scope -- it's a stateless Claude call. The
  // free-tier document *save* limit and org-shared *access* both already
  // apply correctly at the one place they actually mean something --
  // POST /api/documents -- so duplicating that check here would gate a
  // concept (org-shared access) that doesn't apply to this endpoint.
  // What generation actually needed was traceability + abuse throttling,
  // which the auth + rate limit above now provide.
  const identity = user ? `user:${user.id}` : `ip:${getClientIp(req)}`;
  const maxRequests = user ? AUTHENTICATED_RATE_LIMIT : ANONYMOUS_RATE_LIMIT;

  const { limited } = await checkAndIncrementRateLimit(supabase, identity, maxRequests);
  if (limited) {
    res.setHeader('Retry-After', '3600');
    return res.status(429).json({
      error: 'rate_limited',
      message: user
        ? "You're generating documents too quickly. Please wait a bit and try again."
        : "You've reached the demo limit for this hour. Sign up for unlimited access, or try again later."
    });
  }

  try {
    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 4096,
      messages: [
        {
          role: 'user',
          content: `Write a complete ${documentType || 'legal'} document based on the request below. Return only the document text, with no preamble or commentary.\n\n${prompt}`
        }
      ]
    });

    const content = message.content
      .filter((block) => block.type === 'text')
      .map((block) => block.text)
      .join('\n')
      .trim();

    // Minimal traceability -- addresses "no way to trace requests back to
    // a real user or org" from the report without building a full usage-
    // metering table (see the report's note on a possible future
    // per-plan monthly generation quota, which would want one).
    console.log(`Document generated by ${identity}`);

    return res.status(200).json({ content });
  } catch (error) {
    console.error('Error generating document:', error);
    return res.status(500).json({ error: 'Unable to generate document' });
  }
}
